version: '3.9'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydb
      - JWT_SECRET=your_secret_key
      - JWT_EXPIRATION_TIME=86400
      - COOKIE_EXPIRE = 1d

    depends_on:
      - mongo

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "3000:80"
    volumes:
      - ./client:/app
    depends_on:
      - server

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
